---
- name: Ensure SSH keys don't already exist
  stat: 
    path: /home/{{ ansible_ssh_user }}/.ssh/id_rsa
  become: yes
  become:_user: dataops
  become_method: sudo
  register: ssh_key
  tags: 
    - ssh-keys

- name: Generate SSH keys
  when: inventory_hostname in groups['pan1'] and ssh_key.stat.exists == False
  user: name={{ ansible_ssh_user }} generate_ssh_key=yes

- neme: Get id_rsa.pub
  when: inventory_hostname in groups['pan1']
  shell: cat /home/{{ ansible_ssh_user }}/.ssh/id_rsa.pub
  register: id_rsa_pub


- name: Add authorized keys to all hosts
  shell: echo {{ id_rsa_pub.stdout }} >> /home/{{ ansible_ssh_user }}/.ssh/authorized_keys
  delegate_to: "{{ item }}"
  with_items: 
    - "{{ groups['pan2'] }}"
    - "{{ groups['pan3'] }}"
  when: id_rsa_pub.stdout is defined

 
