---
- name: Check if zookeeper tar exists
  stat: path=/home/{{ ansible_ssh_user }}/keshab/zookeeper-3.4.6.tar.gz
  register: zookeeper_exists

- name: Download the zookeeper binary
  get_url:
    url: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
    dest: /home/{{ ansible_ssh_user }}/keshab/
  when: not zookeeper_exists.stat.exists

- name: check if zookeeper file is there
  stat: path=/home/{{ ansible_ssh_user }}/keshab/zookeeper-3.4.6
  register: zookeeper_file_exists

- name: Untar the given zookeeper file
  unarchive:
    src: /home/{{ ansible_ssh_user }}/keshab/zookeeper-3.4.6.tar.gz
    dest: /home/{{ ansible_ssh_user }}/keshab
    copy: no
  when: not zookeeper_file_exists.stat.exists

