---
- name: Check if zookeeper tar exists
  stat: path=/home/dataops/keshab/zookeeper-3.4.6.tar.gz
  register: zookeeper_exists

- name: Download the zookeeper binary
  get_url: 
    url: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
    dest: /home/dataops/keshab/
  when: not zookeeper_exists.stat.exists

- name: check if zookeeper file is there
  stat: path=/home/dataops/keshab/zookeeper-3.4.6
  register: zookeeper_file_exists

- name: Untar the given zookeeper file
  unarchive: 
    src: /home/dataops/keshab/zookeeper-3.4.6.tar.gz
    dest: /home/dataops/keshab
    copy: no
  when: not zookeeper_file_exists.stat.exists

- name: create the zookeeper.properties file
  copy:
    src: /home/dataops/keshab/zookeeper-3.4.6/conf/zoo_sample.cfg
    dest: /home/dataops/keshab/zookeeper-3.4.6/conf/zookeeper.properties
    remote_src: yes
    owner: dataops
    group: dataops
    mode: 0775

- name: change the dataDir in zookeeper.properties
  lineinfile:
    path: /home/dataops/keshab/zookeeper-3.4.6/conf/zookeeper.properties
    regexp: '^dataDir='
    line: 'dataDir=/home/dataops/keshab/zookeeper/data'

- name: Edit the zookeeper.properties file
  blockinfile:
    path: /home/dataops/keshab/zookeeper-3.4.6/conf/zookeeper.properties
    block: |
      server.1=pan1:2888:3888
      server.2=pan2:2888:3888
      server.3=pan3:2888:3888
