---
- name: Check if hadoop already exists
  stat: path= /home/{{ ansible_ssh_user }}/keshab/hadoop-3.0.0.tar.gz
  register: hadoop_tar_exists

- name: Download hadoop
  get_url: 
    url: https://archive.apache.org/dist/hadoop/core/hadoop-3.0.0/hadoop-3.0.0.tar.gz
    dest: /home/{{ ansible_ssh_user }}/keshab
  when: not hadoop_tar_exists.stat.exists

- name: Check if the Untar is done
  stat: path= /home/{{ ansible_ssh_user }}/keshab/hadoop-3.0.0.tar.gz
  register: hadoop_file_exists

- name: Untar the binary file
  become: yes
  unarchive:
    src: /home/{{ ansible_ssh_user }}/keshab/hadoop-3.0.0.tar.gz
    dest: /home/{{ ansible_ssh_user }}/keshab/
    copy: no
  when: not hadoop_file_exists.stat.exists

- name: Fix the ownership of hadoop directory
  file:
    path: /home/{{ ansible_ssh_user }}/keshab/hadoop-3.0.0/
    recurse: yes
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0700
