---
- name: check if there is hadoop before
  stat: path=/opt/hadoop-3.0.0.tar.gz
  register: tar_exists

- name: Download Hadoop binary
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-3.0.0/hadoop-3.0.0.tar.gz
    dest: /opt/
  when: not tar_exists.stat.exists

- name: check if hadoop file is already there
  stat: path=/opt/hadoop-3.0.0
  register: file_exists

- name: Untar the downloaded hadoop file
  become: yes
  command: tar -xvzf /opt/hadoop-3.0.0.tar.gz -C  /opt
  when: not file_exists.stat.exists
