---
- name: Fix the ownership of directory
#  file: dest=/home/dataops owner=dataops group=dataops mode=0775 recurse=yes
  file:
    path: /home/{{ ansible_ssh_user }}/keshab
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes
    mode: 0700

